from PyQt6 import QtCore, QtGui, QtWidgets
import os
import datetime
from PyQt6.QtGui import QIcon, QPixmap

class ResourceHelper:
    @staticmethod
    def get_path(relative_path):
        base_path = os.path.dirname(os.path.abspath(__file__))
        return os.path.join(base_path, relative_path)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(830, 500)
        MainWindow.setMinimumSize(QtCore.QSize(830, 620))
        MainWindow.setMaximumSize(QtCore.QSize(830, 620))
        
        icon_path = ResourceHelper.get_path('../assets/logo.ico')
        icon = QIcon()
        icon.addPixmap(QPixmap(icon_path), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)

        MainWindow.setIconSize(QtCore.QSize(80, 30))
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(209, -1, 640, 600))
        self.stackedWidget.setMaximumSize(QtCore.QSize(640, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label = QtWidgets.QLabel(parent=self.page_1)
        self.label.setGeometry(QtCore.QRect(200, 90, 201, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(ResourceHelper.get_path('../assets/itm-white.png')))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.page_1)
        self.label_3.setGeometry(QtCore.QRect(0, 250, 621, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.page_1)
        self.label_2.setGeometry(QtCore.QRect(0, 180, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_4 = QtWidgets.QLabel(parent=self.page_2)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(-10, 0, 631, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(parent=self.page_2)
        self.label_6.setGeometry(QtCore.QRect(50, 85, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_IMM = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit_IMM.setGeometry(QtCore.QRect(140, 80, 351, 31))
        self.lineEdit_IMM.setObjectName("lineEdit_IMM")
        self.btn_IMM = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_IMM.setGeometry(QtCore.QRect(500, 80, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_IMM.setFont(font)
        self.btn_IMM.setObjectName("btn_IMM")
        self.pushButton_submit = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_submit.setGeometry(QtCore.QRect(250, 550, 121, 41))
        self.pushButton_submit.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.lineEdit_TCM = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit_TCM.setGeometry(QtCore.QRect(140, 120, 351, 31))
        self.lineEdit_TCM.setObjectName("lineEdit_TCM")
        self.label_7 = QtWidgets.QLabel(parent=self.page_2)
        self.label_7.setGeometry(QtCore.QRect(50, 125, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.btn_TCM = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_TCM.setGeometry(QtCore.QRect(500, 120, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_TCM.setFont(font)
        self.btn_TCM.setObjectName("btn_TCM")
        self.label_9 = QtWidgets.QLabel(parent=self.page_2)
        self.label_9.setGeometry(QtCore.QRect(50, 165, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.btn_BEK = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_BEK.setGeometry(QtCore.QRect(500, 160, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_BEK.setFont(font)
        self.btn_BEK.setObjectName("btn_BEK")
        self.lineEdit_BEK = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit_BEK.setGeometry(QtCore.QRect(140, 160, 351, 31))
        self.lineEdit_BEK.setObjectName("lineEdit_BEK")
        self.lineEdit_GPK = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit_GPK.setGeometry(QtCore.QRect(140, 200, 351, 31))
        self.lineEdit_GPK.setObjectName("lineEdit_GPK")
        self.label_11 = QtWidgets.QLabel(parent=self.page_2)
        self.label_11.setGeometry(QtCore.QRect(50, 205, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.btn_GPK = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_GPK.setGeometry(QtCore.QRect(500, 200, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_GPK.setFont(font)
        self.btn_GPK.setObjectName("btn_GPK")
        self.lineEdit_JBG = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit_JBG.setGeometry(QtCore.QRect(140, 240, 351, 31))
        self.lineEdit_JBG.setObjectName("lineEdit_JBG")
        self.btn_JBG = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_JBG.setGeometry(QtCore.QRect(500, 240, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_JBG.setFont(font)
        self.btn_JBG.setObjectName("btn_JBG")
        self.label_12 = QtWidgets.QLabel(parent=self.page_2)
        self.label_12.setGeometry(QtCore.QRect(50, 245, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.lineEdit_TIS = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit_TIS.setGeometry(QtCore.QRect(140, 280, 351, 31))
        self.lineEdit_TIS.setObjectName("lineEdit_TIS")
        self.label_13 = QtWidgets.QLabel(parent=self.page_2)
        self.label_13.setGeometry(QtCore.QRect(30, 279, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.btn_TIS = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_TIS.setGeometry(QtCore.QRect(500, 280, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_TIS.setFont(font)
        self.btn_TIS.setObjectName("btn_TIS")
        self.label_19 = QtWidgets.QLabel(parent=self.page_2)
        self.label_19.setGeometry(QtCore.QRect(30, 360, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.lineEdit_output = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit_output.setGeometry(QtCore.QRect(140, 360, 351, 31))
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.lineEdit_summary = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit_summary.setGeometry(QtCore.QRect(140, 400, 351, 31))
        self.lineEdit_summary.setObjectName("lineEdit_summary")
        self.btn_output = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_output.setGeometry(QtCore.QRect(500, 360, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_output.setFont(font)
        self.btn_output.setObjectName("btn_output")
        self.btn_summary = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_summary.setGeometry(QtCore.QRect(500, 400, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_summary.setFont(font)
        self.btn_summary.setObjectName("btn_summary")
        self.label_20 = QtWidgets.QLabel(parent=self.page_2)
        self.label_20.setGeometry(QtCore.QRect(140, 361, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_27 = QtWidgets.QLabel(parent=self.page_2)
        self.label_27.setGeometry(QtCore.QRect(140, 425, 155, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.page_2)
        self.label_28.setGeometry(QtCore.QRect(30, 400, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.page_2)
        self.label_29.setGeometry(QtCore.QRect(30, 480, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(parent=self.page_2)
        self.label_30.setGeometry(QtCore.QRect(280, 462, 130, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_30.setObjectName("label_30")
        # --- This Day label ---
        self.label_31 = QtWidgets.QLabel(parent=self.page_2)
        self.label_31.setGeometry(QtCore.QRect(30, 440, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        self.label_31.setFont(font)
        self.label_31.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.label_31.setObjectName("label_31")

                
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.comboBoxThisMonth = QtWidgets.QComboBox(parent=self.page_2)
        self.comboBoxThisMonth.setGeometry(QtCore.QRect(140, 480, 85, 31))
        self.comboBoxThisMonth.setEditable(False)
        self.comboBoxThisMonth.setMaxVisibleItems(10)
        self.comboBoxThisMonth.setObjectName("comboBoxThisMonth")
        self.spinBoxOutlookDate = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBoxOutlookDate.setGeometry(QtCore.QRect(285, 480, 70, 31))
        self.spinBoxOutlookDate.setRange(1, 31)  # tanggal valid
        self.spinBoxOutlookDate.setObjectName("spinBoxOutlookDate")
        self.spinBoxOutlookYear = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBoxOutlookYear.setGeometry(QtCore.QRect(480, 480, 81, 31))
        self.spinBoxOutlookYear.setValue(datetime.datetime.now().year)
        self.spinBoxOutlookYear.setRange(2000, 2100)  # batasan tahun
        self.spinBoxOutlookYear.setObjectName("spinBoxOutlookYear")
        self.comboBoxOutlookMonth = QtWidgets.QComboBox(parent=self.page_2)
        self.comboBoxOutlookMonth.setGeometry(QtCore.QRect(375, 480, 85, 31))
        self.comboBoxOutlookMonth.setEditable(False)
        self.comboBoxOutlookMonth.setObjectName("comboBoxOutlookMonth")
        self.spinBox_thisDay = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_thisDay.setGeometry(QtCore.QRect(140, 440, 61, 31))
        self.spinBox_thisDay.setRange(1, 31)  # tanggal 1..31
        self.spinBox_thisDay.setValue(QtCore.QDate.currentDate().day())  # default: hari ini
        self.spinBox_thisDay.setObjectName("spinBox_thisDay")
        
        self.btn_SUM = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_SUM.setGeometry(QtCore.QRect(500, 320, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_SUM.setFont(font)
        self.btn_SUM.setObjectName("btn_SUM")
        self.label_21 = QtWidgets.QLabel(parent=self.page_2)
        self.label_21.setGeometry(QtCore.QRect(30, 319, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.lineEdit_SUM = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit_SUM.setGeometry(QtCore.QRect(140, 320, 351, 31))
        self.lineEdit_SUM.setObjectName("lineEdit_SUM")
        self.label_22 = QtWidgets.QLabel(parent=self.page_2)
        self.label_22.setGeometry(QtCore.QRect(130, 60, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton_process = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_process.setEnabled(True)
        self.pushButton_process.setGeometry(QtCore.QRect(230, 190, 171, 101))
        self.pushButton_process.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(ResourceHelper.get_path('../assets/power-on.png')), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_process.setIcon(icon1)
        self.pushButton_process.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_process.setAutoExclusive(False)
        self.pushButton_process.setObjectName("pushButton_process")
        self.label_24 = QtWidgets.QLabel(parent=self.page_3)
        self.label_24.setGeometry(QtCore.QRect(0, 140, 611, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setEnabled(True)
        self.page_4.setObjectName("page_4")
        self.lineEdit_Raw3rdParty = QtWidgets.QLineEdit(parent=self.page_4)
        self.lineEdit_Raw3rdParty.setGeometry(QtCore.QRect(150, 190, 331, 31))
        self.lineEdit_Raw3rdParty.setObjectName("lineEdit_Raw3rdParty")
        self.lineEdit_Draft3rdParty = QtWidgets.QLineEdit(parent=self.page_4)
        self.lineEdit_Draft3rdParty.setGeometry(QtCore.QRect(150, 250, 331, 31))
        self.lineEdit_Draft3rdParty.setObjectName("lineEdit_Draft3rdParty")
        self.pushButton_Raw3rdParty = QtWidgets.QPushButton(parent=self.page_4)
        self.pushButton_Raw3rdParty.setGeometry(QtCore.QRect(500, 190, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton_Raw3rdParty.setFont(font)
        self.pushButton_Raw3rdParty.setObjectName("pushButton_Raw3rdParty")
        self.label_17 = QtWidgets.QLabel(parent=self.page_4)
        self.label_17.setGeometry(QtCore.QRect(60, 260, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.pushButton_Draft3rdParty = QtWidgets.QPushButton(parent=self.page_4)
        self.pushButton_Draft3rdParty.setGeometry(QtCore.QRect(500, 250, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton_Draft3rdParty.setFont(font)
        self.pushButton_Draft3rdParty.setObjectName("pushButton_Draft3rdParty")
        self.label_25 = QtWidgets.QLabel(parent=self.page_4)
        self.label_25.setGeometry(QtCore.QRect(60, 190, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(parent=self.page_4)
        self.label_26.setEnabled(True)
        self.label_26.setGeometry(QtCore.QRect(-10, 90, 631, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.pushButton_Start3rdParty = QtWidgets.QPushButton(parent=self.page_4)
        self.pushButton_Start3rdParty.setGeometry(QtCore.QRect(240, 330, 121, 41))
        self.pushButton_Start3rdParty.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_Start3rdParty.setFont(font)
        self.pushButton_Start3rdParty.setObjectName("pushButton_Start3rdParty")
        self.stackedWidget.addWidget(self.page_4)
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 20, 61, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(ResourceHelper.get_path('../assets/ITM_logo.png')))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 60, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.pushButton_Home = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Home.setEnabled(True)
        self.pushButton_Home.setGeometry(QtCore.QRect(10, 170, 191, 41))
        self.pushButton_Home.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_Home.setFont(font)
        self.pushButton_Home.setAutoFillBackground(False)
        self.pushButton_Home.setCheckable(True)
        self.pushButton_Home.setChecked(False)
        self.pushButton_Home.setAutoRepeat(False)
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.pushButton_Automation = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Automation.setEnabled(True)
        self.pushButton_Automation.setGeometry(QtCore.QRect(10, 230, 191, 41))
        self.pushButton_Automation.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_Automation.setFont(font)
        self.pushButton_Automation.setObjectName("pushButton_Automation")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(180, 10, 61, 631))
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Welcome to the Automation System"))
        self.label_2.setText(_translate("MainWindow", "PT Indo Tambangraya Megah Tbk"))
        self.label_4.setText(_translate("MainWindow", "Complete the Required Data"))
        self.label_6.setText(_translate("MainWindow", "IMM"))
        self.btn_IMM.setText(_translate("MainWindow", "Browse"))
        self.pushButton_submit.setText(_translate("MainWindow", "Submit"))
        self.label_7.setText(_translate("MainWindow", "TCM"))
        self.btn_TCM.setText(_translate("MainWindow", "Browse"))
        self.label_9.setText(_translate("MainWindow", "BEK"))
        self.btn_BEK.setText(_translate("MainWindow", "Browse"))
        self.label_11.setText(_translate("MainWindow", "GPK"))
        self.btn_GPK.setText(_translate("MainWindow", "Browse"))
        self.btn_JBG.setText(_translate("MainWindow", "Browse"))
        self.label_12.setText(_translate("MainWindow", "JBG"))
        self.label_13.setText(_translate("MainWindow", "TIS"))
        self.btn_TIS.setText(_translate("MainWindow", "Browse"))
        self.label_19.setText(_translate("MainWindow", "Output"))
        self.btn_output.setText(_translate("MainWindow", "Browse"))
        self.label_20.setText(_translate("MainWindow", "*Draft for Power BI Dashboard source"))
        self.btn_SUM.setText(_translate("MainWindow", "Browse"))
        self.label_21.setText(_translate("MainWindow", "SUM Quality"))
        self.label_22.setText(_translate("MainWindow", "*Production Report Data"))
        self.label_24.setText(_translate("MainWindow", "Start Automation Process"))
        self.pushButton_Raw3rdParty.setText(_translate("MainWindow", "Select File"))
        self.label_17.setText(_translate("MainWindow", "Draft File"))
        self.pushButton_Draft3rdParty.setText(_translate("MainWindow", "Select File"))
        self.label_25.setText(_translate("MainWindow", "Raw File"))
        self.label_26.setText(_translate("MainWindow", "Complete the Required Data for 3rd Party"))
        self.label_27.setText(_translate("MainWindow", "*File Summary for Pro Outlook"))
        self.label_28.setText(_translate("MainWindow", "Summary"))
        self.btn_summary.setText(_translate("MainWindow", "Browse"))
        self.label_29.setText(_translate("MainWindow", "This Month"))
        self.label_30.setText(_translate("MainWindow", "*Pro Outlook Sheet Name"))
        self.label_31.setText(_translate("MainWindow", "This Day"))
        self.pushButton_Start3rdParty.setText(_translate("MainWindow", "Start Process"))
        self.label_10.setText(_translate("MainWindow", "PT Indo Tambangraya Megah Tbk"))
        self.pushButton_Home.setText(_translate("MainWindow", "Home"))
        self.pushButton_Automation.setText(_translate("MainWindow", "Automation"))
