from PyQt6 import QtCore, QtGui, QtWidgets
import os
from PyQt6.QtGui import QIcon, QPixmap

class ResourceHelper:
    @staticmethod
    def get_path(relative_path):
        base_path = os.path.dirname(os.path.abspath(__file__))
        return os.path.join(base_path, relative_path)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(830, 500)
        MainWindow.setMinimumSize(QtCore.QSize(830, 500))
        MainWindow.setMaximumSize(QtCore.QSize(830, 500))  
        
        icon_path = ResourceHelper.get_path('../assets/logo.ico')
        icon = QIcon()
        icon.addPixmap(QPixmap(icon_path), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setIconSize(QtCore.QSize(80, 30))
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(209, 0, 621, 500))
        self.stackedWidget.setMaximumSize(QtCore.QSize(640, 500))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label = QtWidgets.QLabel(parent=self.page_1)
        self.label.setGeometry(QtCore.QRect(200, 90, 201, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(ResourceHelper.get_path('../assets/itm-white.png')))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.page_1)
        self.label_3.setGeometry(QtCore.QRect(-10, 250, 621, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.page_1)
        self.label_2.setGeometry(QtCore.QRect(-10, 190, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.stackedWidget.addWidget(self.page_1)
        # ================================
        # 📌 PAGE 2 : Weekly Report
        # ================================
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")

        # Judul halaman
        self.label_4 = QtWidgets.QLabel(parent=self.page_2)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(-10, 30, 631, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")

        # ================================
        # 📌 Input File Path
        # ================================
        # Summary File
        self.label_5 = QtWidgets.QLabel(parent=self.page_2)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight |
                                  QtCore.Qt.AlignmentFlag.AlignTrailing |
                                  QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")

        self.lineEdit_summary = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit_summary.setGeometry(QtCore.QRect(140, 100, 341, 31))
        self.lineEdit_summary.setObjectName("lineEdit_summary")

        self.btn_summary = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_summary.setGeometry(QtCore.QRect(500, 100, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_summary.setFont(font)
        self.btn_summary.setObjectName("btn_summary")

        # Final File
        self.label_6 = QtWidgets.QLabel(parent=self.page_2)
        self.label_6.setGeometry(QtCore.QRect(50, 160, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight |
                                  QtCore.Qt.AlignmentFlag.AlignTrailing |
                                  QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")

        self.lineEdit_final = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit_final.setGeometry(QtCore.QRect(140, 150, 341, 31))
        self.lineEdit_final.setObjectName("lineEdit_final")

        self.btn_final = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_final.setGeometry(QtCore.QRect(500, 150, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.btn_final.setFont(font)
        self.btn_final.setObjectName("btn_final")

        # ================================
        # 📌 Month 1
        # ================================
        self.label_11 = QtWidgets.QLabel(parent=self.page_2)
        self.label_11.setGeometry(QtCore.QRect(140, 210, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")

        self.spinBox_headerMonth1 = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_headerMonth1.setGeometry(QtCore.QRect(140, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.spinBox_headerMonth1.setFont(font)
        self.spinBox_headerMonth1.setMaximum(9999)
        self.spinBox_headerMonth1.setObjectName("spinBox_headerMonth1")

        self.label_14 = QtWidgets.QLabel(parent=self.page_2)
        self.label_14.setGeometry(QtCore.QRect(230, 210, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")

        self.spinBox_dataCountMonth1 = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_dataCountMonth1.setGeometry(QtCore.QRect(230, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.spinBox_dataCountMonth1.setFont(font)
        self.spinBox_dataCountMonth1.setMaximum(9999)
        self.spinBox_dataCountMonth1.setObjectName("spinBox_dataCountMonth1")

        # ================================
        # 📌 Month 2
        # ================================
        self.label_12 = QtWidgets.QLabel(parent=self.page_2)
        self.label_12.setGeometry(QtCore.QRect(140, 280, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.spinBox_headerMonth2 = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_headerMonth2.setGeometry(QtCore.QRect(140, 300, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.spinBox_headerMonth2.setFont(font)
        self.spinBox_headerMonth2.setMaximum(9999)
        self.spinBox_headerMonth2.setObjectName("spinBox_headerMonth2")

        self.label_16 = QtWidgets.QLabel(parent=self.page_2)
        self.label_16.setGeometry(QtCore.QRect(230, 280, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")

        self.spinBox_dataCountMonth2 = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_dataCountMonth2.setGeometry(QtCore.QRect(230, 300, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.spinBox_dataCountMonth2.setFont(font)
        self.spinBox_dataCountMonth2.setMaximum(9999)
        self.spinBox_dataCountMonth2.setObjectName("spinBox_dataCountMonth2")

        # ================================
        # 📌 Month 3
        # ================================
        self.label_13 = QtWidgets.QLabel(parent=self.page_2)
        self.label_13.setGeometry(QtCore.QRect(140, 350, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")

        self.spinBox_headerMonth3 = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_headerMonth3.setGeometry(QtCore.QRect(140, 370, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.spinBox_headerMonth3.setFont(font)
        self.spinBox_headerMonth3.setMaximum(9999)
        self.spinBox_headerMonth3.setObjectName("spinBox_headerMonth3")

        self.label_15 = QtWidgets.QLabel(parent=self.page_2)
        self.label_15.setGeometry(QtCore.QRect(230, 350, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")

        self.spinBox_dataCountMonth3 = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_dataCountMonth3.setGeometry(QtCore.QRect(230, 370, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.spinBox_dataCountMonth3.setFont(font)
        self.spinBox_dataCountMonth3.setMaximum(9999)
        self.spinBox_dataCountMonth3.setObjectName("spinBox_dataCountMonth3")

        # ================================
        # 📌 Month 4
        # ================================
        self.label_20 = QtWidgets.QLabel(parent=self.page_2)
        self.label_20.setGeometry(QtCore.QRect(400, 210, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")

        self.spinBox_headerMonth4 = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_headerMonth4.setGeometry(QtCore.QRect(400, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.spinBox_headerMonth4.setFont(font)
        self.spinBox_headerMonth4.setMaximum(9999)
        self.spinBox_headerMonth4.setObjectName("spinBox_headerMonth4")

        self.label_19 = QtWidgets.QLabel(parent=self.page_2)
        self.label_19.setGeometry(QtCore.QRect(490, 210, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")

        self.spinBox_dataCountMonth4 = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_dataCountMonth4.setGeometry(QtCore.QRect(490, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.spinBox_dataCountMonth4.setFont(font)
        self.spinBox_dataCountMonth4.setMaximum(9999)
        self.spinBox_dataCountMonth4.setObjectName("spinBox_dataCountMonth4")

        self.checkBox_enableMonth4 = QtWidgets.QCheckBox(parent=self.page_2)
        self.checkBox_enableMonth4.setGeometry(QtCore.QRect(570, 235, 21, 20))
        self.checkBox_enableMonth4.setText("")
        self.checkBox_enableMonth4.setObjectName("checkBox_enableMonth4")

        # ================================
        # 📌 Month 5
        # ================================
        self.label_28 = QtWidgets.QLabel(parent=self.page_2)
        self.label_28.setGeometry(QtCore.QRect(400, 280, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")

        self.spinBox_headerMonth5 = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_headerMonth5.setGeometry(QtCore.QRect(400, 300, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.spinBox_headerMonth5.setFont(font)
        self.spinBox_headerMonth5.setMaximum(9999)
        self.spinBox_headerMonth5.setObjectName("spinBox_headerMonth5")

        self.label_29 = QtWidgets.QLabel(parent=self.page_2)
        self.label_29.setGeometry(QtCore.QRect(490, 280, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")

        self.spinBox_dataCountMonth5 = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_dataCountMonth5.setGeometry(QtCore.QRect(490, 300, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.spinBox_dataCountMonth5.setFont(font)
        self.spinBox_dataCountMonth5.setMaximum(9999)
        self.spinBox_dataCountMonth5.setObjectName("spinBox_dataCountMonth5")

        self.checkBox_enableMonth5 = QtWidgets.QCheckBox(parent=self.page_2)
        self.checkBox_enableMonth5.setGeometry(QtCore.QRect(570, 305, 21, 20))
        self.checkBox_enableMonth5.setText("")
        self.checkBox_enableMonth5.setObjectName("checkBox_enableMonth5")

        # ================================
        # 📌 Month 6
        # ================================
        self.label_31 = QtWidgets.QLabel(parent=self.page_2)
        self.label_31.setGeometry(QtCore.QRect(400, 350, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")

        self.spinBox_headerMonth6 = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_headerMonth6.setGeometry(QtCore.QRect(400, 370, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.spinBox_headerMonth6.setFont(font)
        self.spinBox_headerMonth6.setMaximum(9999)
        self.spinBox_headerMonth6.setObjectName("spinBox_headerMonth6")

        self.label_32 = QtWidgets.QLabel(parent=self.page_2)
        self.label_32.setGeometry(QtCore.QRect(490, 350, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")

        self.spinBox_dataCountMonth6 = QtWidgets.QSpinBox(parent=self.page_2)
        self.spinBox_dataCountMonth6.setGeometry(QtCore.QRect(490, 370, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.spinBox_dataCountMonth6.setFont(font)
        self.spinBox_dataCountMonth6.setMaximum(9999)
        self.spinBox_dataCountMonth6.setObjectName("spinBox_dataCountMonth6")

        self.checkBox_enableMonth6 = QtWidgets.QCheckBox(parent=self.page_2)
        self.checkBox_enableMonth6.setGeometry(QtCore.QRect(570, 375, 21, 20))
        self.checkBox_enableMonth6.setText("")
        self.checkBox_enableMonth6.setObjectName("checkBox_enableMonth6")

        # ================================
        # 📌 Select Week + Submit
        # ================================
        self.label_7 = QtWidgets.QLabel(parent=self.page_2)
        self.label_7.setGeometry(QtCore.QRect(60, 230, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight |
                                  QtCore.Qt.AlignmentFlag.AlignTrailing |
                                  QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setObjectName("label_7")

        self.label_9 = QtWidgets.QLabel(parent=self.page_2)
        self.label_9.setGeometry(QtCore.QRect(20, 430, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight |
                                  QtCore.Qt.AlignmentFlag.AlignTrailing |
                                  QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setObjectName("label_9")

        self.comboBox_week = QtWidgets.QComboBox(parent=self.page_2)
        self.comboBox_week.setGeometry(QtCore.QRect(140, 425, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.comboBox_week.setFont(font)
        self.comboBox_week.setObjectName("comboBox_week")

        self.pushButton_submit = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_submit.setGeometry(QtCore.QRect(450, 420, 121, 41))
        self.pushButton_submit.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setObjectName("pushButton_submit")

        # Label tambahan (keterangan)
        self.label_21 = QtWidgets.QLabel(parent=self.page_2)
        self.label_21.setGeometry(QtCore.QRect(60, 300, 61, 20))
        self.label_21.setFont(QtGui.QFont("Arial", 12))
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight |
                                   QtCore.Qt.AlignmentFlag.AlignTrailing |
                                   QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_21.setObjectName("label_21")

        self.label_22 = QtWidgets.QLabel(parent=self.page_2)
        self.label_22.setGeometry(QtCore.QRect(60, 370, 61, 20))
        self.label_22.setFont(QtGui.QFont("Arial", 12))
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight |
                                   QtCore.Qt.AlignmentFlag.AlignTrailing |
                                   QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_22.setObjectName("label_22")

        self.label_23 = QtWidgets.QLabel(parent=self.page_2)
        self.label_23.setGeometry(QtCore.QRect(320, 230, 61, 20))
        self.label_23.setFont(QtGui.QFont("Arial", 12))
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight |
                                   QtCore.Qt.AlignmentFlag.AlignTrailing |
                                   QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_23.setObjectName("label_23")

        self.label_27 = QtWidgets.QLabel(parent=self.page_2)
        self.label_27.setGeometry(QtCore.QRect(320, 300, 61, 20))
        self.label_27.setFont(QtGui.QFont("Arial", 12))
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight |
                                   QtCore.Qt.AlignmentFlag.AlignTrailing |
                                   QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_27.setObjectName("label_27")

        self.label_30 = QtWidgets.QLabel(parent=self.page_2)
        self.label_30.setGeometry(QtCore.QRect(320, 370, 61, 20))
        self.label_30.setFont(QtGui.QFont("Arial", 12))
        self.label_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight |
                                   QtCore.Qt.AlignmentFlag.AlignTrailing |
                                   QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_30.setObjectName("label_30")

        # Add page_2 ke stackedWidget
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton_process = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_process.setEnabled(True)
        self.pushButton_process.setGeometry(QtCore.QRect(230, 60, 171, 101))
        self.pushButton_process.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(ResourceHelper.get_path('../assets/power-on.png')), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_process.setIcon(icon1)
        self.pushButton_process.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_process.setAutoExclusive(False)
        self.pushButton_process.setObjectName("pushButton_process")
        self.label_24 = QtWidgets.QLabel(parent=self.page_3)
        self.label_24.setGeometry(QtCore.QRect(0, 20, 611, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.textEdit_log = QtWidgets.QTextEdit(parent=self.page_3)
        self.textEdit_log.setGeometry(QtCore.QRect(60, 190, 501, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit_log.setFont(font)
        self.textEdit_log.setObjectName("textEdit_log")
        self.pushButton_end = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_end.setGeometry(QtCore.QRect(490, 430, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_end.setFont(font)
        self.pushButton_end.setObjectName("pushButton_end")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setEnabled(True)
        self.page_4.setObjectName("page_4")
        self.lineEdit_Raw3rdParty = QtWidgets.QLineEdit(parent=self.page_4)
        self.lineEdit_Raw3rdParty.setGeometry(QtCore.QRect(150, 190, 331, 31))
        self.lineEdit_Raw3rdParty.setObjectName("lineEdit_Raw3rdParty")
        self.lineEdit_Draft3rdParty = QtWidgets.QLineEdit(parent=self.page_4)
        self.lineEdit_Draft3rdParty.setGeometry(QtCore.QRect(150, 250, 331, 31))
        self.lineEdit_Draft3rdParty.setObjectName("lineEdit_Draft3rdParty")
        self.pushButton_Raw3rdParty = QtWidgets.QPushButton(parent=self.page_4)
        self.pushButton_Raw3rdParty.setGeometry(QtCore.QRect(500, 190, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton_Raw3rdParty.setFont(font)
        self.pushButton_Raw3rdParty.setObjectName("pushButton_Raw3rdParty")
        self.label_17 = QtWidgets.QLabel(parent=self.page_4)
        self.label_17.setGeometry(QtCore.QRect(60, 260, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.pushButton_Draft3rdParty = QtWidgets.QPushButton(parent=self.page_4)
        self.pushButton_Draft3rdParty.setGeometry(QtCore.QRect(500, 250, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton_Draft3rdParty.setFont(font)
        self.pushButton_Draft3rdParty.setObjectName("pushButton_Draft3rdParty")
        self.label_25 = QtWidgets.QLabel(parent=self.page_4)
        self.label_25.setGeometry(QtCore.QRect(60, 190, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(parent=self.page_4)
        self.label_26.setEnabled(True)
        self.label_26.setGeometry(QtCore.QRect(-10, 90, 621, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.pushButton_Start3rdParty = QtWidgets.QPushButton(parent=self.page_4)
        self.pushButton_Start3rdParty.setGeometry(QtCore.QRect(240, 330, 121, 41))
        self.pushButton_Start3rdParty.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_Start3rdParty.setFont(font)
        self.pushButton_Start3rdParty.setObjectName("pushButton_Start3rdParty")
        self.stackedWidget.addWidget(self.page_4)
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 20, 61, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(ResourceHelper.get_path('../assets/ITM_logo.png')))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 60, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.pushButton_Home = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Home.setEnabled(True)
        self.pushButton_Home.setGeometry(QtCore.QRect(10, 140, 191, 41))
        self.pushButton_Home.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_Home.setFont(font)
        self.pushButton_Home.setAutoFillBackground(False)
        self.pushButton_Home.setCheckable(True)
        self.pushButton_Home.setChecked(False)
        self.pushButton_Home.setAutoRepeat(False)
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.pushButton_Performance = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Performance.setEnabled(True)
        self.pushButton_Performance.setGeometry(QtCore.QRect(10, 200, 191, 41))
        self.pushButton_Performance.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_Performance.setFont(font)
        self.pushButton_Performance.setObjectName("pushButton_Performance")
        self.pushButton_3rdParty = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3rdParty.setEnabled(True)
        self.pushButton_3rdParty.setGeometry(QtCore.QRect(10, 260, 191, 41))
        self.pushButton_3rdParty.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_3rdParty.setFont(font)
        self.pushButton_3rdParty.setObjectName("pushButton_3rdParty")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(180, 10, 61, 461))
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automation System"))
        self.label_3.setText(_translate("MainWindow", "Welcome to the Automation System"))
        self.label_2.setText(_translate("MainWindow", "PT Indo Tambangraya Megah Tbk"))
        self.label_4.setText(_translate("MainWindow", "Complete the Required Data for Weekly Report"))
        self.label_5.setText(_translate("MainWindow", "Summary File"))
        self.label_6.setText(_translate("MainWindow", "Final File"))
        self.label_7.setText(_translate("MainWindow", "Month 1"))
        self.label_9.setText(_translate("MainWindow", "Select Week"))
        self.label_11.setText(_translate("MainWindow", "Header"))
        self.label_12.setText(_translate("MainWindow", "Header"))
        self.label_13.setText(_translate("MainWindow", "Header"))
        self.label_14.setText(_translate("MainWindow", "Data Count"))
        self.label_15.setText(_translate("MainWindow", "Data Count"))
        self.label_16.setText(_translate("MainWindow", "Data Count"))
        self.btn_summary.setText(_translate("MainWindow", "Select File"))
        self.btn_final.setText(_translate("MainWindow", "Select File"))
        self.pushButton_submit.setText(_translate("MainWindow", "Submit"))
        self.label_19.setText(_translate("MainWindow", "Data Count"))
        self.label_20.setText(_translate("MainWindow", "Header"))
        self.label_21.setText(_translate("MainWindow", "Month 2"))
        self.label_22.setText(_translate("MainWindow", "Month 3"))
        self.label_23.setText(_translate("MainWindow", "Month 4"))
        self.label_24.setText(_translate("MainWindow", "Start Automation Process"))
        self.pushButton_end.setText(_translate("MainWindow", "End"))
        self.pushButton_Raw3rdParty.setText(_translate("MainWindow", "Select File"))
        self.label_17.setText(_translate("MainWindow", "Draft File"))
        self.pushButton_Draft3rdParty.setText(_translate("MainWindow", "Select File"))
        self.label_25.setText(_translate("MainWindow", "Raw File"))
        self.label_26.setText(_translate("MainWindow", "Complete the Required Data for 3rd Party"))
        self.label_27.setText(_translate("MainWindow", "Month 5"))
        self.label_28.setText(_translate("MainWindow", "Header"))
        self.label_29.setText(_translate("MainWindow", "Data Count"))
        self.label_30.setText(_translate("MainWindow", "Month 6"))
        self.label_31.setText(_translate("MainWindow", "Header"))
        self.label_32.setText(_translate("MainWindow", "Data Count"))
        self.pushButton_Start3rdParty.setText(_translate("MainWindow", "Start Process"))
        self.label_10.setText(_translate("MainWindow", "PT Indo Tambangraya Megah Tbk"))
        self.pushButton_Home.setText(_translate("MainWindow", "Home"))
        self.pushButton_Performance.setText(_translate("MainWindow", "Weekly Report"))
        self.pushButton_3rdParty.setText(_translate("MainWindow", "3rd Party"))